# Generated by Django 4.2.6 on 2023-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Описание')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField()),
            ],
        ),
    ]
