# Generated by Django 4.2.6 on 2023-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(verbose_name='Запланировать на'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=16, verbose_name='Название'),
        ),
    ]
