# Generated by Django 4.2.6 on 2023-10-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_last_modified_note_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AlterField(
            model_name='note',
            name='main_text',
            field=models.TextField(verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, help_text='Опционально', max_length=255, verbose_name='Заголовок'),
        ),
    ]
