# Generated by Django 4.2.6 on 2023-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_options_alter_note_main_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
