# Generated by Django 4.2.6 on 2023-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_tags_alter_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['last_modified']},
        ),
    ]
