# Generated by Django 4.2.6 on 2023-10-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_todo_options_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_completed', 'last_modified']},
        ),
    ]
