# Generated by Django 4.2.6 on 2023-10-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['is_completed', '-last_modified']},
        ),
    ]
